### ISSUE TITLE
I think we should to put a download link of sqlite-jdbcs' or mysql-connector-java's jar on the official website.

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#115]
Maybe like this:
01:50:50 [INFO] ... Other info ...
01:50:50 [INFO] Downloading sqlite-jdbc 3.7.2...
01:50:50 [WARN] Failed to download: sqlite-jdbc 3.7.2
java.net.UnknownHostException: repo.glowstone.net
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at net.glowstone.util.LibraryManager.download(LibraryManager.java:54)
        at net.glowstone.util.LibraryManager.run(LibraryManager.java:42)
        at net.glowstone.GlowServer.start(GlowServer.java:470)
        at net.glowstone.GlowServer.main(GlowServer.java:121)
01:50:50 [INFO] Downloading mysql-connector-java 5.1.34...
01:50:50 [WARN] Failed to download: mysql-connector-java 5.1.34
java.net.UnknownHostException: repo.glowstone.net
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at net.glowstone.util.LibraryManager.download(LibraryManager.java:54)
        at net.glowstone.util.LibraryManager.run(LibraryManager.java:43)
        at net.glowstone.GlowServer.start(GlowServer.java:470)
        at net.glowstone.GlowServer.main(GlowServer.java:121)
01:50:50 [INFO] Scanning plugins...
01:50:50 [INFO] ... Other info ...

For some particular areas such as North Korea it would be a bad experience.

**Comment by SenanYT** [comment]
The owner of the project is from China lol. 

Maybe we could put a download link.

**Comment by DefinitlyEvil** [comment]
Nah, maybe that website is dead. We should put it somewhere else.

**Comment by jlirochon** [comment]
Just for my information, why do we need 2 database connectors ?

**Comment by ghost** [comment]
@jlirochon This is indeed an interesting question ......

**Comment by DefinitlyEvil** [comment]
@jlirochon @mainwindow Some plugins require them.

**Comment by DefinitlyEvil** [comment]
Anyways, let's just keep it downloading from `repo.glowstone.net`.
