### ISSUE TITLE
Some Error

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#133]
21:34:05 [ERROR] Error occurred while pulsing world world
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$EntryIterator.next(Unknown Source)
        at java.util.HashMap$EntryIterator.next(Unknown Source)
        at java.util.HashMap.putMapEntries(Unknown Source)
        at java.util.HashMap.<init>(Unknown Source)
        at net.glowstone.GlowWorld.getTickMap(GlowWorld.java:1739)
        at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1727)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:389)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
And:
21:34:21 [ERROR] Error while loading chunk (22,13)
java.util.zip.ZipException: unknown compression method
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.util.zip.InflaterInputStream.read(Unknown Source)
        at java.io.FilterInputStream.read(Unknown Source)
        at java.io.DataInputStream.readUnsignedByte(Unknown Source)
        at net.glowstone.util.nbt.NBTInputStream.readCompound(NBTInputStream.java:57)
        at net.glowstone.io.anvil.AnvilChunkIoService.read(AnvilChunkIoService.java:66)
        at net.glowstone.ChunkManager.loadChunk(ChunkManager.java:131)
        at net.glowstone.GlowChunk.load(GlowChunk.java:265)
        at net.glowstone.GlowChunk.load(GlowChunk.java:260)
        at net.glowstone.GlowChunk.getSection(GlowChunk.java:359)
        at net.glowstone.GlowChunk.getType(GlowChunk.java:394)
        at net.glowstone.block.GlowBlock.getTypeId(GlowBlock.java:194)
        at net.glowstone.block.GlowBlock.getType(GlowBlock.java:189)
        at net.glowstone.block.GlowBlock.isLiquid(GlowBlock.java:264)
        at net.glowstone.block.blocktype.BlockLiquid.calculateFlow(BlockLiquid.java:93)
        at net.glowstone.block.blocktype.BlockLiquid.receivePulse(BlockLiquid.java:69)
        at net.glowstone.GlowWorld.pulseTickMap(GlowWorld.java:1733)
        at net.glowstone.GlowWorld.pulse(GlowWorld.java:389)
        at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)

**Comment by DefinitlyEvil** [comment]
@mastercoms

**Comment by mastercoms** [comment]
Could you say what was happening when the first error was happening?

And the first one is a bug with the chunk reader, and one of your chunks will reset. I would rather rewrite the reader than try to fix it.

Also, mainwindow, if you could, please move this issue to the GlowstonePlusPlus repository.

**Comment by DefinitlyEvil** [comment]
Maybe his region file is corrupted. xD

**Comment by jlirochon** [comment]
maybe we need world data to see if it's corrupted ?

**Comment by DefinitlyEvil** [comment]
If user for sly terminate the process when shutting down, the world file may corrupt.

**Comment by DefinitlyEvil** [comment]
forcly*

**Comment by ghost** [comment]
When I use PE Client join the server, the first error is:
11:29:17 [ERROR] Error while pulsing
java.lang.NullPointerException
        at org.dragonet.net.packet.minecraft.WindowItemsPacket.encode(WindowItemsPacket.java:47)
        at org.dragonet.net.inf.mcpe.RakNetInterface.sendPacket(RakNetInterface.java:122)
        at org.dragonet.net.inf.mcpe.PENetworkClient.sendPacket(PENetworkClient.java:149)
        at org.dragonet.net.inf.mcpe.MCPESession.send(MCPESession.java:68)
        at org.dragonet.net.inf.mcpe.MCPESession.send(MCPESession.java:73)
        at org.dragonet.net.DragonetSession.setPlayer(DragonetSession.java:230)
        at org.dragonet.net.inf.mcpe.PENetworkClient.handlePacket(PENetworkClient.java:103)
        at org.dragonet.net.inf.mcpe.PENetworkClient.handlePacket(PENetworkClient.java:111)
        at org.dragonet.net.inf.mcpe.PENetworkClient.processPacketBuffer(PENetworkClient.java:71)
        at org.dragonet.net.inf.mcpe.RakNetInterface.handleEncapsulated(RakNetInterface.java:101)
        at org.dragonet.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at org.dragonet.net.inf.mcpe.RakNetInterface.onTick(RakNetInterface.java:80)
        at org.dragonet.DragonetServer.tickUpdate(DragonetServer.java:221)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:173)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by ghost** [comment]
I upload my test log file.
[log-2015-12-09.txt](https://github.com/DragonetMC/Dragonet/files/56316/log-2015-12-09.txt)
