### ISSUE TITLE
Reorganizing the JavaScript methods into different classes/namespaces

### ISSUE THREAD

**Issue by wordandahalf** [DragonetMC/Dragonet-Legacy#21]
I'm thinking of reorganizing the functions so they are more similar to ModPE, since right now there is no organization at all, and it looks a little messy in my opinion.
Here's an example of the new way would be:

```
var Player = new PlayerAPI(); //'Player' can be whatever you want, but is preferred
var World = new WorldAPI();  //""
var Server = new ServerAPI(); //""

function useItem(x, y, z, face, bName, plr)
{
    Player.kill(plr);
    World.setBlock(x, y, z, "WOOL", 0);
    Server.stop("");
}
```

It would also mean that there would be an easier way of adding new functions into the source code; Instead of having to make a new file and add stuff to the Functions class, you would just have to add the method into the 'PlayerAPI', 'WorldAPI', or 'ServerAPI' class.

**Comment by ashquarky** [comment]
I think this could be a great idea, actually. It'd add more flexibility to your script - only importing what you need, and having an easy hub for your stuff.

Just to make sure I've got the idea right, this would be a possible usage of this, correct?:

``` javascript
var Server = new ServerAPI();
var Players = new PlayerAPI();

function onChatSending(player, msg) {
    if (Players.getLocation(player) == new LocationOrWhateverBukkitUses(42, 9001, 64)) {
        Server.runCommand("/msg " + player.name + " You can't say that in MY house!");
        return true;
    } else {
        return false;
    }
}
```

Just as an example. Anyway, if that's about right, I think it'd be great! As more and more functions are added, there's gonna need to be a way of organizing them. It could work really well.

Hmm... this gives me an idea....

#22 , here we come!

**Comment by wordandahalf** [comment]
@QuarkTheAwesome Yea, that would be a correct usage. I guess I'll start changing it later today.

**Comment by Creeperface01** [comment]
Networking code in modscript doesn't work BL says: function doesn't exist.

**Comment by ashquarky** [comment]
@TheMCPEGamer Just thought I should mention that the current implementation... doesn't work. I might not be using it right, but I get this error:

``` java
org.mozilla.javascript.EcmaError: TypeError: Cannot find default value for object. (script#3)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693)
    at org.mozilla.javascript.ScriptRuntime.typeError1(ScriptRuntime.java:3705)
    at org.mozilla.javascript.ScriptableObject.getDefaultValue(ScriptableObject.java:976)
    at org.mozilla.javascript.ScriptableObject.getDefaultValue(ScriptableObject.java:895)
    at org.mozilla.javascript.ScriptRuntime.toString(ScriptRuntime.java:761)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3774)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2269)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2251)
    at org.mozilla.javascript.gen.script_1234._c_onChatSending_1(script:3)
    at org.mozilla.javascript.gen.script_1234.call(script)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
    at org.mozilla.javascript.gen.script_1234.call(script)
    at org.dragonet.rhino.Script.runFunction(Script.java:113)
    at org.dragonet.rhino.api.onChatSending.onChatSending(onChatSending.java:19)
    at org.dragonet.rhino.Rhino.onChatSending(Rhino.java:63)
    at net.glowstone.EventFactory.onPlayerChat(EventFactory.java:120)
    at net.glowstone.entity.GlowPlayer.chat(GlowPlayer.java:1320)
    at net.glowstone.net.handler.play.game.IncomingChatHandler.handle(IncomingChatHandler.java:11)
    at net.glowstone.net.handler.play.game.IncomingChatHandler.handle(IncomingChatHandler.java:7)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.messageReceived(GlowSession.java:523)
    at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:49)
    at net.glowstone.net.pipeline.MessageHandler.channelRead0(MessageHandler.java:15)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by wordandahalf** [comment]
@QuarkTheAwesome Can you post your code? Is this error appearing on the server's start? If it is, it may be a syntax error.

**Comment by ashquarky** [comment]
@TheMCPEGamer This happens whenever I try to call anything from the ServerAPI class.

For example:

``` javascript
var Server = new org.dragonet.rhino.api.functions.ServerAPI();
function onChatSending(player, msg) {
    Server.clientMessage(msg);
    return true;
}
```

will throw an exception whenever I send a chat message.

**Comment by DefinitlyEvil** [comment]
@Creeperface01 The MCPE client needs to use local Android app as a proxy to connect to the server because BL will disable all scripts when connecting to a remote server. I haven't implement thost yet.

**Comment by wordandahalf** [comment]
@QuarkTheAwesome I'll look into this later.

**Comment by DefinitlyEvil** [comment]
@TheMCPEGamer 
The normal mcpe networking: `Client <-> Server`
Dragonet Addon required networking: `Client <-> Addon App(Redirect UDP packets) <-> Server`

**Comment by ashquarky** [comment]
@TheMCPEGamer Just so you know, I managed to fix the issue I was having (the TypeError). I'm not sure what I did, but now it's fine!

Now I can start the ScriptAPI. ;3

**Comment by wordandahalf** [comment]
@QuarkTheAwesome Thanks! :D
