### ISSUE TITLE
crafting - duplication and item removal glitches

### ISSUE THREAD

**Issue by ghost** [DragonetMC/Dragonet-Legacy#49]
First of all, I would like to say that I do not know if these bugs are a problem with glowstone or dragonet. If this is the wrong place to report these bugs then please tell me. 

While crafting, shift-click does not work, items have duplications in the top row of the inventory, and some items are sometimes removed from the inventory upon closing the inventory. Another bug was when I was trying to craft a wooden pickaxe, in which the sticks kept duplicating, and when I closed my inventory, all of my items except for 32 sticks were gone. I am using dragonet version 0.0.2-preR5. Here is the log:

```
2015/07/10 20:42:09 [SEVERE] Error while handling WindowClickMessage(id=7, slot=0, button=0, transaction=3, mode=0, item=ItemStack{WOOD x 4}) (handler: WindowClickHandler)
java.lang.NullPointerException
    at org.dragonet.inventory.ItemList.cloneList(ItemList.java:84)
    at org.dragonet.inventory.ItemList.tryToRemove(ItemList.java:46)
    at net.glowstone.inventory.crafting.CraftingManager.removeItems(CraftingManager.java:102)
    at net.glowstone.inventory.GlowCraftingInventory.craft(GlowCraftingInventory.java:123)
    at net.glowstone.inventory.GlowCraftingInventory.craft(GlowCraftingInventory.java:112)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:406)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:42:12 [INFO] lobuo: [rejected] WindowClickMessage(id=7, slot=5, button=0, transaction=5, mode=0, item=ItemStack{LOG x 63})
2015/07/10 20:42:16 [INFO] lobuo: [rejected] WindowClickMessage(id=7, slot=0, button=0, transaction=7, mode=0, item=ItemStack{WOOD x 4})
2015/07/10 20:42:54 [SEVERE] Error while handling WindowClickMessage(id=8, slot=0, button=0, transaction=7, mode=0, item=ItemStack{STICK x 4}) (handler: WindowClickHandler)
java.lang.NullPointerException
    at org.dragonet.inventory.ItemList.cloneList(ItemList.java:84)
    at org.dragonet.inventory.ItemList.tryToRemove(ItemList.java:46)
    at net.glowstone.inventory.crafting.CraftingManager.removeItems(CraftingManager.java:102)
    at net.glowstone.inventory.GlowCraftingInventory.craft(GlowCraftingInventory.java:123)
    at net.glowstone.inventory.GlowCraftingInventory.craft(GlowCraftingInventory.java:112)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:406)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:42:55 [INFO] lobuo: [rejected] WindowClickMessage(id=8, slot=8, button=1, transaction=8, mode=0, item=null)
2015/07/10 20:43:01 [SEVERE] Error while handling WindowClickMessage(id=8, slot=8, button=0, transaction=12, mode=0, item=ItemStack{WOOD x 1}) (handler: WindowClickHandler)
java.lang.NullPointerException
    at net.glowstone.inventory.crafting.GlowMapZoomMatcher.getResult(GlowMapZoomMatcher.java:21)
    at org.bukkit.inventory.DynamicRecipe.matches(DynamicRecipe.java:40)
    at net.glowstone.inventory.crafting.CraftingManager.getCraftingRecipe(CraftingManager.java:145)
    at net.glowstone.inventory.GlowCraftingInventory.getRecipe(GlowCraftingInventory.java:162)
    at net.glowstone.inventory.GlowCraftingInventory.setItem(GlowCraftingInventory.java:42)
    at org.bukkit.inventory.InventoryView.setItem(InventoryView.java:138)
    at net.glowstone.inventory.GlowInventoryView.setItem(GlowInventoryView.java:53)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:293)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:43:02 [SEVERE] Error while handling WindowClickMessage(id=8, slot=8, button=0, transaction=13, mode=0, item=ItemStack{STICK x 4}) (handler: WindowClickHandler)
java.lang.NullPointerException
    at net.glowstone.inventory.crafting.GlowMapZoomMatcher.getResult(GlowMapZoomMatcher.java:21)
    at org.bukkit.inventory.DynamicRecipe.matches(DynamicRecipe.java:40)
    at net.glowstone.inventory.crafting.CraftingManager.getCraftingRecipe(CraftingManager.java:145)
    at net.glowstone.inventory.GlowCraftingInventory.getRecipe(GlowCraftingInventory.java:162)
    at net.glowstone.inventory.GlowCraftingInventory.setItem(GlowCraftingInventory.java:42)
    at org.bukkit.inventory.InventoryView.setItem(InventoryView.java:138)
    at net.glowstone.inventory.GlowInventoryView.setItem(GlowInventoryView.java:53)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:277)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:43:02 [SEVERE] Error while handling WindowClickMessage(id=8, slot=8, button=0, transaction=14, mode=0, item=ItemStack{STICK x 8}) (handler: WindowClickHandler)
java.lang.NullPointerException
    at net.glowstone.inventory.crafting.GlowMapZoomMatcher.getResult(GlowMapZoomMatcher.java:21)
    at org.bukkit.inventory.DynamicRecipe.matches(DynamicRecipe.java:40)
    at net.glowstone.inventory.crafting.CraftingManager.getCraftingRecipe(CraftingManager.java:145)
    at net.glowstone.inventory.GlowCraftingInventory.getRecipe(GlowCraftingInventory.java:162)
    at net.glowstone.inventory.GlowCraftingInventory.setItem(GlowCraftingInventory.java:42)
    at org.bukkit.inventory.InventoryView.setItem(InventoryView.java:138)
    at net.glowstone.inventory.GlowInventoryView.setItem(GlowInventoryView.java:53)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:277)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:43:06 [SEVERE] Error while handling WindowClickMessage(id=8, slot=8, button=0, transaction=15, mode=0, item=ItemStack{STICK x 16}) (handler: WindowClickHandler)
java.lang.NullPointerException
    at net.glowstone.inventory.crafting.GlowMapZoomMatcher.getResult(GlowMapZoomMatcher.java:21)
    at org.bukkit.inventory.DynamicRecipe.matches(DynamicRecipe.java:40)
    at net.glowstone.inventory.crafting.CraftingManager.getCraftingRecipe(CraftingManager.java:145)
    at net.glowstone.inventory.GlowCraftingInventory.getRecipe(GlowCraftingInventory.java:162)
    at net.glowstone.inventory.GlowCraftingInventory.setItem(GlowCraftingInventory.java:42)
    at org.bukkit.inventory.InventoryView.setItem(InventoryView.java:138)
    at net.glowstone.inventory.GlowInventoryView.setItem(GlowInventoryView.java:53)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:277)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:43:12 [SEVERE] Error while handling WindowClickMessage(id=8, slot=8, button=1, transaction=22, mode=0, item=null) (handler: WindowClickHandler)
java.lang.NullPointerException
    at net.glowstone.inventory.crafting.GlowMapZoomMatcher.getResult(GlowMapZoomMatcher.java:21)
    at org.bukkit.inventory.DynamicRecipe.matches(DynamicRecipe.java:40)
    at net.glowstone.inventory.crafting.CraftingManager.getCraftingRecipe(CraftingManager.java:145)
    at net.glowstone.inventory.GlowCraftingInventory.getRecipe(GlowCraftingInventory.java:162)
    at net.glowstone.inventory.GlowCraftingInventory.setItem(GlowCraftingInventory.java:42)
    at org.bukkit.inventory.InventoryView.setItem(InventoryView.java:138)
    at net.glowstone.inventory.GlowInventoryView.setItem(GlowInventoryView.java:53)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.process(WindowClickHandler.java:288)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:35)
    at net.glowstone.net.handler.play.inv.WindowClickHandler.handle(WindowClickHandler.java:30)
    at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
    at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
    at net.glowstone.net.GlowSession.pulse(GlowSession.java:453)
    at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:177)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
2015/07/10 20:43:16 [INFO] lobuo: [rejected] WindowClickMessage(id=8, slot=5, button=0, transaction=28, mode=0, item=ItemStack{STICK x 1})

```

**Comment by RandomAltThing** [comment]
This looks like glowstone because of the error contains alot of
<code>net.glowstone</code> package names. Yes, this is the correct place to report issues/bugs.

**Comment by RandomAltThing** [comment]
I see that the error is a **NullPointerException** so I will add the bug label

**Comment by DefinitlyEvil** [comment]
I believe this is Glowstone++'s problem. @SpaceManiac 
Tagging @Glowstone++ team.

**Comment by DefinitlyEvil** [comment]
@GlowstonePlusPlus

**Comment by ethsmith** [comment]
Yeah the crafting bugs have been annoying me, I am gonna try to find out what's wrong with crafting and if I can't I guess I will let @mastercoms have a go at it, he's better than me at this stuff :P

**Comment by DefinitlyEvil** [comment]
@TekkitCommando Well I sincerly really hope that you guys can join our project and become one of us. xD

**Comment by ethsmith** [comment]
xD I don't know how @mastercoms or @deathcap feels but I don't mind our 2 teams working together at points :smile:

**Comment by mastercoms** [comment]
I have identified the problem and will fix it soon.

**Comment by ethsmith** [comment]
Ah Your Awesome @mastercoms I just got home so haven't even looked yet :P

**Comment by mastercoms** [comment]
Problem should be fixed. Merge from upstream, and you should be good. If there are any other crafting bugs you've found, please tell me, as I'm starting a crafting bug massacre.

Bugs will be telling their children for generations about this.

**Comment by ethsmith** [comment]
xD

**Comment by wordandahalf** [comment]
@mastercoms It's like a bug genocide!

Kill all the bugs!

**Comment by DefinitlyEvil** [comment]
You guys are genius! :D

**Comment by DefinitlyEvil** [comment]
This can close now. ;)

**Comment by mastercoms** [comment]
https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/cb28eb57864f6db67ab06f14dc0b761bace6ddfb fixes pretty much all crafting issues, except 1 minor, cosmetic bug, which is listed in the commit comments.

**Comment by mastercoms** [comment]
Please direct any further issues to do with Minecraft PC Edition crafting to https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/issues/76

**Comment by mastercoms** [comment]
Fixed an additional bug in: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/24070db09d941b71e4b02117d875310f4564139d

**Comment by DefinitlyEvil** [comment]
Okay. ;)
