### ISSUE TITLE
Failed to download: sqlite-jdbc 3.7.2 and  Failed to download: mysql-connector-java 5.1.34

### ISSUE THREAD

**Issue by uiue** [DragonetMC/Dragonet-Legacy#74]
02:36:37 [警告] Failed to download: sqlite-jdbc 3.7.2
java.net.ConnectException: 连接超时
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at java.net.URL.openStream(URL.java:1037)
    at net.glowstone.util.LibraryManager.download(LibraryManager.java:54)
    at net.glowstone.util.LibraryManager.run(LibraryManager.java:42)
    at net.glowstone.GlowServer.start(GlowServer.java:470)
    at net.glowstone.GlowServer.main(GlowServer.java:121)
02:36:37 [信息] Downloading mysql-connector-java 5.1.34...
02:37:40 [警告] Failed to download: mysql-connector-java 5.1.34
java.net.ConnectException: 连接超时
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:618)
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at java.net.URL.openStream(URL.java:1037)
    at net.glowstone.util.LibraryManager.download(LibraryManager.java:54)
    at net.glowstone.util.LibraryManager.run(LibraryManager.java:43)
    at net.glowstone.GlowServer.start(GlowServer.java:470)
    at net.glowstone.GlowServer.main(GlowServer.java:121)

**Comment by mastercoms** [comment]
You're using an old build of Dragonet.

**Comment by uiue** [comment]
I am using "0.0.2-alpha (MCPC 1.8.0-1.8.7, MCPE 0.11.0-0.11.4 alpha): KINDA STABLE ;)", this is old build?

**Comment by ethsmith** [comment]
0.0.3alpha was out i thought

**Comment by DefinitlyEvil** [comment]
@uiue @TekkitCommando Nope, 0.0.3 is under development. And 0.0.2-alpha is not a well-developed build and it still has lots of bugs.

**Comment by DragonTester** [comment]
A Fu*king Chinese Cracker. What do you want? Cracking some server? Funny.

**Comment by DragonTester** [comment]
Chinese government to let you undo the firewall can be downloaded.

**Comment by Darkhax** [comment]
I also experienced this issue. You can temporarily fix it by manually downloading the mysql-connector-java-5.1.34.jar and sqlite-jdbc-3.7.1.jar from their official sources and place them in the lib directory. Just run a google search for the file name if you're having trouble finding them.
